### ISSUE TITLE
Inconsistent number of policy documents with references

### ISSUE THREAD

**Issue by nsorros** [wellcometrust/policytool#131]
Marta from I&A asked me to report, among other numbers, the number of policy documents that contained a reference (or references section).

There are two ways to get this number which give an odd result. One is to ask how many policy documents have a references section according to the scraper? Note that the numbers are calculated only for policy organizations that we have run the scraper and parser.
```
SELECT
	count(distinct publication.file_hash)
from publication
inner join provider on provider.id=publication.id_provider
inner join publications_sections on publications_sections.id_publication=publication.id
where provider.name in ('who_iris', 'msf', 'unicef', 'nice');
```
This returns **4650**

On the other hand, we can ask the question how many unique policy documents the parsed references table has under the assumption that if there is a references section at least one reference will appear in the database.
```
select
	count(distinct file_hash)
from document
```
This returns **5124**

This is very odd because it seems that references were parsed from documents that have no references section. If anything, someone would expect the opposite, a smaller number on the second query indicating that we have not parsed references from some policy documents.

This came up because when I reported back the first number Marta pointed out that the number is smaller than last time even though the number of policy documents have increased. The number that was reported previous time by @lizgzil was 4792 and I am assuming that it came from the second calculation, @lizgzil can verify.

Can we investigate this discrepancy? For now, I will get back to her with the second number as I am assuming this is the correct apple to apple comparison with previous time.

**Comment by lizgzil** [comment]
I think I would have calculated it based off the first calculation actually.
The second is flawed since there might be times where a references section is scraped but actually no references are predicted (it seems unlikely, but I wouldn't rule it out of happening if the scrape was just special characters maybe). We could check this.

But yes, the discrepancy between 4650 and 5124 is weird and I agree you'd expect the difference to be the other way around if anything!

In the second calculation do you also apply the filter of only using 'who_iris', 'msf', 'unicef', 'nice' publications?

**Comment by nsorros** [comment]
You do not have to apply it in the second calculation as we have not run the parser for gov or parliament. @SamDepardieu can confirm.

**Comment by SamDepardieu** [comment]
This is fairly odd 🤔

**Comment by SamDepardieu** [comment]
What could be is that we have some document we parsed reference from before one of the few database reset we did, but it seems unlikely to me that it could lead to such a big difference.

At the moment I don't have a clear idea of what's actually going on, but I'll investigate that

**Comment by MartaMoratti** [comment]
thank you all for looking into it,. I would be interested in getting the total figures and % of policy docs scraped by organisation as well as the % of docs with ref sections by organisation.  (X% of WHO docs has a ref section, Y% of NICE, etc). wonder there is a pattern. thanks!

**Comment by MartaMoratti** [comment]
Also, as part of the discrepancies we found between the file shared with me and the database - that need further investigations, i found that 1041 unique publications had at least 1 (policy) citation. Only 28 publications had more than 5 (policy) citations. Nick's figure was 82. again, super thanks for looking into it!

**Comment by lizgzil** [comment]
@MartaMoratti The correct number of policy documents that contained a reference (or references section) to use is 4650. 
I think the discrepancy between the old (4792) and new numbers is just because we've changed a few things to the algorithm and more docs may have been scraped in the time gap.

**Comment by MartaMoratti** [comment]
thanks Liz! I am a bit surprised that more scraping returns less docs with ref sections? is that reasonable? I trust your knowledge on that so happy to whichever figure you will give me. I would  also like to know the total number of policy docs scraped in total and if possible the breakdown of policy docs with ref section by policy org. thanksss, Marta

**Comment by lizgzil** [comment]
@MartaMoratti Sorry I read the numbers the other way round when writing that! Indeed more time passing would mean we have _more_ to scrape not less. However, I'm not entirely sure whether the algorithm changes will have lead to more or less policy docs with references sections being scraped, but either way I'm not surprised the numbers have changed a bit.

I think the info Nick emailed you about should answer your second question, but let us know if not :)

**Comment by nsorros** [comment]
As per @hblanks suggestion we should not use or trust the database. I have already updated @MartaMoratti about using the numbers from the output of the policy tool.
