### ISSUE TITLE
fuzzymatch doesn't allow you to input just 1 publication

### ISSUE THREAD

**Issue by lizgzil** [wellcometrust/policytool#138]
`fuzzymatch.py` needs to be rewritten in such a way to input one publication, since it might not always be multiple. I tried to fuzzy match one publication against many and got an error:
```
>>> test_publication = test_publications.iloc[0]
>>> test_publication
Unnamed: 0                                                      0
Title           How to write a successful grant or fellowship ...
Reference id                                       pub.1044375419
Type                                                     Positive
Journal                                                      None
PubYear                                                      None
Authors                                                      None
Issue                                                        None
Volume                                                       None
Document id                                                     0
Document uri                                                 None
Name: 0, dtype: object
>>> match_data = fuzzy_matcher.match_vectorised(test_publication)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/gallaghe/Code/policytool/utils/fuzzymatch.py", line 33, in match_vectorised
    inplace=True
  File "/Users/gallaghe/Code/policytool/build/virtualenv/lib/python3.7/site-packages/pandas/core/series.py", line 3889, in dropna
    'argument "{0}"'.format(list(kwargs.keys())[0]))
TypeError: dropna() got an unexpected keyword argument "subset"
```

There is an error if we convert it to a one row dataframe too:
```
>>> match_data = fuzzy_matcher.match_vectorised(pd.DataFrame(test_publication))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/gallaghe/Code/policytool/utils/fuzzymatch.py", line 33, in match_vectorised
    inplace=True
  File "/Users/gallaghe/Code/policytool/build/virtualenv/lib/python3.7/site-packages/pandas/core/frame.py", line 4285, in dropna
    raise KeyError(list(np.compress(check, subset)))
KeyError: ['Title']
```

**Comment by nsorros** [comment]
I am investigating

**Comment by nsorros** [comment]
Passing a series would not work as a dataframe is expected.

It turns out that when going from one Series to a dataframe the columns go to different rows for some reason. Try `test_publication.to_frame().transpose()` and it should work. Verify and close the issue if it does.

**Comment by lizgzil** [comment]
that does work, but shouldn't we still fix this code so that the user can input a one row or multiple row dataframe (without having to know they have to add `.to_frame().transpose()`) ? 
could simply add this to fuzzymatch.py:
```
if len(predicted_publications)==1:
     predicted_publications = predicted_publications.to_frame().transpose()
```

**Comment by nsorros** [comment]
well, this requires some more thinking. the problem is that the function has promised that it operates on a dataframe with certain columns and it does that even if that dataframe is one row. the problem you encountered is that you passed a Series not a Dataframe and the function did not work which is expected.

one way around this, it to detect a series and do the transformation. you can do that by `if isinstance(predicted_publications, pd.Series):` instead of `len(predicted_publications)==1:`. doing so slighlty complicates the code bear in mind but it might be ok to do so to allow for the functionality of running one publication which is a series.

**Comment by lizgzil** [comment]
Closing since this is no longer an issue because of the new refactoring of fuzzymatching
