### ISSUE TITLE
policytool "YEAR" of policydoc

### ISSUE THREAD

**Issue by MartaMoratti** [wellcometrust/policytool#159]
as we are updating the analysis for the WSF report, (due very soon!) I have been  asked if possible to add/update data to cover policy citations from all 2018. Previous figures seems to have covered policy docs at to June 2018. I cannot find the year of the policy doc in the excel files you guys shared with me. IS that sth you can easily pull out - report on? will it be possible to re-run the analysis to cover policy docs up to end of 2018 (or end of September 2018 - if possible.)
Pls lemme know when and if feasible for you to provide this information. thanks!
Marta

**Comment by lizgzil** [comment]
Hi @MartaMoratti, we do have some year information which I think we could include, but only for WHO and NICE. The UNICEF and MSF data doesn't contain publication year, so it won't be possible to include this info for all the data anyway.

@nsorros I assume you didn't filter the results you gave to Marta to only include certain publication years?

**Comment by nsorros** [comment]
I shared these data with @MartaMoratti so closing this. Feel free to open it if it is not resolved.
