### ISSUE TITLE
Most cited wellcome publication is a false positive

### ISSUE THREAD

**Issue by nsorros** [wellcometrust/policytool#164]
> Hey Nick,
>
> 
>
>A quick one before I go on leave (to keep you busy while I am on the beach):
>
>pub.1021807036
>
>This publication is supposed by be cited on 14 policy docs (which is relatively high! So it ended up in our sample of top cases. But we cannot find the exact publication in the refs of the policy docs.
>
>There are a lot of publications with similar titles but not that one.
>
>Can it be an “error”? is there a way to tell in advance / know how confident the algorithm is in the prediction?
>
>IS it useful to provide you with this sort of feedback to improve the accuracy or not really?
>
>(see u when I am back! but  Sioned will be working on this tomorrow so if u have any quick reactions, ?pls let us know!)
>
>Thanks,
>Marta

**Comment by nsorros** [comment]
This prediction seems to be coming from the exact match strategy which means that we have identified an exact mention of one of our publications in the references text. As this is an exact match, we do not provide confidence for the algorithm as this is is not a machine learning prediction, you consider the confidence to be close to 1 for such matches.

For context, the publication that was matched was "Attention deficit hyperactivity disorder" and some example policy documents are https://apps.who.int/iris/bitstream/handle/10665/200168/9780869707876.pdf?sequence=1&isAllowed=y and https://apps.who.int/iris/bitstream/handle/10665/254678/WHO-FWC-IHE-17.01-eng.pdf?sequence=1&isAllowed=y. 

The error occurs because the references that are being matched contain this title as a substring. This is a known limitation of the tool that we are working towards solving.

It is very useful to provide us with this feedback as this feed into the prioritization of what to work next.

**Comment by aoifespenge** [comment]
Yes - seems to be very useful to get this feedback! This reminds me that I think a really easy to use feedback mechanism on the interface will be very useful for our model, but also it will encourage a good relationship between the users and the model for 'co-learning' and trust building, as outline in this great article by Google: https://medium.com/google-design/human-centered-machine-learning-a770d10562cd @dd207 a feature consideration for future iterations/releases?

**Comment by lizgzil** [comment]
Shall we close this, since further investigation (explained here https://github.com/wellcometrust/policytool/blob/master/docs/problems.md) has lead to more understanding about this issue, and so I've opened two other issues related to this  "Attention deficit hyperactivity disorder" paper - https://github.com/wellcometrust/policytool/issues/181 and https://github.com/wellcometrust/policytool/issues/180
