### ISSUE TITLE
Change grab_section to not capitalise section name

### ISSUE THREAD

**Issue by lizgzil** [wellcometrust/policytool#195]
In https://github.com/wellcometrust/policytool/blob/master/policytool/pdf_parser/main.py we look for sections titles listed in https://github.com/wellcometrust/policytool/blob/master/policytool/resources/section_keywords.txt, and add them to a dictionary.

Currently we capitalise the names of these from the dictionary, and use this as the dictionary keys. The code is 
```
if section:
   section_dict[title.title()] = section
   if section_dict.get(title.title()):
        section_dict[title.title()].append(section)
  else:
        section_dict[title.title()] = [section]
```
but we shouldnt capitalise since it causes confusion when comparing to 'section_keywords.txt'
```
if section:
   section_dict[title] = section
   if section_dict.get(title):
        section_dict[title].append(section)
  else:
        section_dict[title] = [section]
```

This will cause knock-on effects where we try to access 'References' in places (which has it's own issues since we should be looking for anything in 'section_keywords.txt' rather than explicitly looking for 'References').

**Comment by nsorros** [comment]
@lizgzil make sure you use the right keyword to automatically close the github issues when you merge a PR https://help.github.com/en/articles/closing-issues-using-keywords

In this case, adding issue between fixes and the issue number probably broke it
