### ISSUE TITLE
Output file not linking correctly in deployed code

### ISSUE THREAD

**Issue by lizgzil** [wellcometrust/policytool#20]
In `parser_references>reference` the `id_document` does not seem to be correct as it links to a predicted title (in `parser_references>document.id`) which is nothing like the actually title. Otherwise the output match info (the file hash and pubmed id) seem to be correctly matched.

This situation does not happen when the code is run locally. 

LOCALLY RUN OUPUT:
**file hash:** e54e005e8f9f736189e52fbd03a3d9f2
Predicted title: (2006) Does breastfeeding influence risk of   type 2 diabetes in later life?, A quantitative analysis of published evidence
**Actual title:** Does breastfeeding influence risk of type 2   diabetes in later life? A quantitative analysis of published evidence.
**Pubmed id:** pub.1077320364

RDS OUTPUT:
**file hash:** e54e005e8f9f736189e52fbd03a3d9f2
**Predicted title:** and   cardiovascular disease: metaanalysis of prospective studies
**Actual title:** Does breastfeeding influence risk of type 2   diabetes in later life? A quantitative analysis of published evidence.
**Pubmed id:** pub.1077320364

**Comment by lizgzil** [comment]
I've checked and this is still an issue (although this particular example is no longer in the matched data).

**Comment by lizgzil** [comment]
![screenshot 2019-01-07 at 16 18 31](https://user-images.githubusercontent.com/15956065/50779312-e7cf6080-1297-11e9-87d4-241fdfcff366.png)

**Comment by SamDepardieu** [comment]
We're not using RDS anymore and the ouputs have completely changed. Closing this.
