### ISSUE TITLE
Parliament Scraping is huge

### ISSUE THREAD

**Issue by SamDepardieu** [wellcometrust/policytool#226]
Hey guys!
I'm working on fixing the parliament scraping, which is at the moment not working great. On my inspections, I realized that at the moment we are scraping all from the website, from 1980 to 2019, which represent 2 milions document:
<img width="433" alt="image" src="https://user-images.githubusercontent.com/6536364/64358616-b3669c80-cffe-11e9-9ada-05b4e6b9f93d.png">

 While it is possible to scrape them, it would involve changing a bit how we proceed. So the question is:
 - From these 2m documents, do we actually need everything?

Most of these are completly irelevant to what we're doing, and even though I think it would be beneficial to improve the way we scrape our documents, I'm pretty sure less than 20% of these documents are actually relevant, and even less are actually useful.

I'd like your point of view on this before spending some dev time to fit the needs of scraping quickly all those pdfs.

Here's the search api: https://search-material.parliament.uk/search
Please do have a look around, and let's narrow down the number of documents that are interesting to us! :)

**Comment by lizgzil** [comment]
Good point, I have also looked through some of these in the past and really struggled to find anything relevant to us.

During my Reach/Uber comparison I can see whether Uber look at the parliament website, and if so, I will see if we can learn anything from their results to filter our scrape.

**Comment by nsorros** [comment]
Did we agree anything on that? Did you discuss this with @dd207? One thing we can investigate on our end is a classifier based on url or on the metadata that predicts whether there will be a reference section? That said, it feels that the most useful thing to do would be for Dawn to make a decision on this.

**Comment by aoifespenge** [comment]
https://docs.google.com/presentation/d/137LMvVOGnohh9U1_L2cTqQAC_eM6lKyDycOjb6KCoew/edit#slide=id.g5c9b18e3a0_0_180 The June research gave a lot of insight into what funders want to see from our scrapes. Whether is it important to people depends on things like: Does the document capture decisions, how influential is the writer, does it indicate practice change, etc.

**Comment by dd207** [comment]
Hi all,

Thanks for raising. I've looked at the document types that are available here: https://www.parliament.uk/site-information/using-this-website/searchhelp/

Actual legislation, bills and business statements often have little or no references so not relevant to us. We should prioritise the following: 

**High importance**
- Select committee reports 
- Select committee evidence 
- Research briefings 

**Medium importance**
- Debates
- Oral contributions 
Note - these will obviously be very large but could be interesting stuff in there for analysis later down the line. 

**Low importance**
Laid papers
Business statements 
Bills
Early Day motions 
Urgent Questions 
Statements 
House of Commons and House of Lords papers
