### ISSUE TITLE
FuzzyMatchRefs.who_iris produces no matches in staging

### ISSUE THREAD

**Issue by hblanks** [wellcometrust/policytool#236]
Observations in staging:

1. I've loaded all EPMC pubs into ES via the policy DAG.
1. I've then run the FuzzyMatchRefs.who_iris task in the ploicy DAG.
1. I've then checked the S3 output and found it empty.

I've then done the same in localdev and observed the same. Also in localdev:

1. I've verified number of records in ES:
    ```
    $ python -m policytool.elastic.count epmc-metadata
    5523383
    ```

This seems different than what @nsorros saw when he ran it locally. Now trying to run it locally using the staging inputs in S3 with more logging to see what's going on...

**Comment by lizgzil** [comment]
I haven't looked into this properly, but it may have something to do with switching from Dimensions to EPMC without having changed column names which are still hard coded.

e.g. `check_publications_file` in `refparse` should be failing since I assume the EPMC data doesnt have 'uber_id'?

**Comment by hblanks** [comment]
Thanks, @lizgzil ! Seems like the first fix here was, indeed, just fixing names:

```
         body = {
             "query": {
                 "match": {
-                    "title": {
+                    "doc.title": {
                         "query": title,
                         "minimum_should_match": f"{self.should_match_threshold}%"
                     }
```

But, this has surfaced some new issues with the quality of references coming down into this step of the pipe. I'll create a new issue for that. @nsorros  - we will seek help from someone in data science on data quality of ExtractRefs (but probably also for validating data quality in later steps, too) next week if that's feasible.

**Comment by hblanks** [comment]
(Merged, will verify in staging early this coming week)
