### ISSUE TITLE
Make README Method 1 clearer

### ISSUE THREAD

**Issue by lizgzil** [wellcometrust/policytool#25]
This might be me being not very command line savy, but either way, I found the readme 'How to use it' Method 1 difficult to follow and didn't get it to work. I found Method 2 fine, probably because it was obvious what needed to be edited.

Firstly, it's not clear what `SCRAPER_FILE` and `REFERENCES_FILE` should look like, should they contain the file path and name or just the file name? An example would be nice.

More generally, I didn't know how to edit `python manage.py run_predict [OPTIONS] SCRAPER_FILE REFERENCES_FILE` in such a way to make it run, my best guess failed:

![screen shot 2018-12-13 at 3 59 03 pm](https://user-images.githubusercontent.com/15956065/49952579-1d309a80-fef4-11e8-9caf-8bca4f893761.png)

**Comment by hblanks** [comment]
Thanks for a great writeup, @lizgzil !

**Comment by hblanks** [comment]
Maybe we're getting closer to dropping this method from the README and deprecate manage.py, in favor of other methods now?

**Comment by nsorros** [comment]
In favor 👍

**Comment by lizgzil** [comment]
I'm going to close this since we have another issue to update the readme
