### ISSUE TITLE
Don't require SENTRY_DSN for local development

### ISSUE THREAD

**Issue by nsorros** [wellcometrust/policytool#34]
When running locally, even though sentry should be disable we still need to initialiase the environment variable. I suggest we remove this dependency when running locally, if not then I suggest we add to the documentation that this variable is needed. @SamDepardieu @hblanks

**Comment by hblanks** [comment]
Thanks! Agreed, we probably shouldn't require this when developing.

**Comment by hblanks** [comment]
Agreed, long term policy tool needs to be able to run without sentry for those developing it on their own.

**Comment by hblanks** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Support running reference parser without SENTRY_DSN](https://trello.com/c/cD4JhICc/549-support-running-reference-parser-without-sentrydsn)
