### ISSUE TITLE
Fix main to account for times when no Title column is predicted

### ISSUE THREAD

**Issue by lizgzil** [wellcometrust/policytool#41]
Now that we process each policy document one by one we run into a problem occasionally where no Title is predicted in the parsing of references, and therefore the fuzzy matching step will break (since there is no 'Title' column to match on).
e.g.
<img width="660" alt="screenshot 2019-01-30 at 15 32 27" src="https://user-images.githubusercontent.com/15956065/51992306-ab60e000-24a4-11e9-8d35-91b49954f696.png">

If this occurs the fuzzy match step should be skipped in main and a blank `all_match_data.csv` should be created (or not created at all).

**Comment by nsorros** [comment]
thanks for opening this issue @lizgzil. why don't you submit a fix as well?

**Comment by peter337** [comment]
@lizgzil @nsorros 
Still not familiar with the data/code, so may be completely off-track here, but might it be better to include a dummy Title column when creating the source data? I.e. if there's not already a Title column, add one containing only blanks. That way, if we need code in future which references the Title column, we won't need to write another 'if' check.
I think it's also better practice for tabulated data, as it helps keep the size and column names of the data standard and predictable.

**Comment by lizgzil** [comment]
@peter337 may be a good option, thanks.
