### ISSUE TITLE
Fix predict for when 'Predicted Category' is not found

### ISSUE THREAD

**Issue by lizgzil** [wellcometrust/policytool#43]
I came across an error in `predict` where `predict_all['Predicted Category']` was not found, see screenshot:

<img width="642" alt="screenshot 2019-01-31 at 11 44 49" src="https://user-images.githubusercontent.com/15956065/52209100-bcca3380-287a-11e9-8a5f-b0f600249af1.png">

Perhaps worth checking whether `reference_components` is ever empty, since it shouldn't be, but this could give rise to no 'Predicted Category' field.

**Comment by nsorros** [comment]
It would be good practice i think when we report bugs, to include code to reproduce the error.
