### ISSUE TITLE
Fix setting organisation regex 

### ISSUE THREAD

**Issue by lizgzil** [wellcometrust/policytool#55]
At the moment the organisation doesn't change by the user's input. If it's not set as an environmental variable then the organisation is set to nice and the regex is set to \n (see `settings.py`).

We need it so that the input file to be parsed with automatically set the ORGANISATION variable to the relevant organisation and the correct regex is picked.

A s a temporary hack we tell the user (in the README) to set the ORGANISATION environmental variable before running the parser, but this is prone to human errors.

**Comment by nsorros** [comment]
I am closing this as we have now moved to using a universal regex. Reopen if needed
