### ISSUE TITLE
Local parse and match is quite different to database results

### ISSUE THREAD

**Issue by lizgzil** [wellcometrust/policytool#80]
I ran the parser locally for the latest JSONs for each organisation found in S3, but my results were quite different from the database.

I used `uber_api_publications.csv` to match against, this is 105,207 publications. I used the model and vectoriser in S3 (`reference_parser_models/RefSorter_classifier.pkl` and `reference_parser_models/RefSorter_vectorizer.pkl`). The code also used the new universal regex for each organisation. 

The results are:

organisation | Scrape date | Number documents | Number references-doc matches | Time of whole process
-- | -- | -- | -- | --
Who_iris | who_iris_20190214 | 5174 | 1249 | 3586 secs
Nice | nice_20190131 | 280 | 15 | 280 secs
Unicef | unicef_20190131 | 105 | 37 | 78 secs
Msf | msf_20190131 | 151 | 2 | 90 secs
Gov_uk | gov_uk_20190116 | 1893 | 38 | 552 secs
Parliament | parliament_20190125 | 196 | 14 | 56 secs
TOTAL |   | 7799 documents | 1355   ( + 9 with no url, + 2 from url www.fao.org) = 1366 matches | 1.3 hours

However in the database `scraper.publication` has 213,782 documents and in `parser_references.reference` there are 4784 matches.

Two reasons for differences could be:
1. possibly the latest data in the database was found with older scraped data than the ones I used,
2. the latest data in the database was probably found using the old regexes (this code was merged 14th feb)

However, in both cases we might not expect such a large difference results.
Does anyone have any other ideas of why there might be such a difference?

**Comment by hblanks** [comment]
@SamDepardieu  - if you have a minute to look into this today or tomorrow, we should. (A good habit for OSS is to characterize bugs or provide feedback on them within 2 working days.)

**Comment by nsorros** [comment]
Any update on this?

**Comment by SamDepardieu** [comment]
This is probably due to the scraper beeing killed before it sends the json to s3. It writes to the db everytime an item comes through, though it only push the json at the end of the process.

This will eventually get fixed as we are removing the pdf parsing task from the scraper and moving it to a separate process. 

I'm leaving this open to keep you updated 👍

**Comment by nsorros** [comment]
As per @hblanks suggestion we should not use or trust the database.

**Comment by hblanks** [comment]
Yes, see my discussion which cc'd @nsorros  in March, https://github.com/wellcometrust/datalabs/issues/232#issuecomment-473937296
