### ISSUE TITLE
Consolidate 4 methods to 1 for running the parser

### ISSUE THREAD

**Issue by nsorros** [wellcometrust/policytool#92]
I suggest we remove method 1 which uses the **manage.py** and method 2 that uses **settings.py** and leave method 3 as the suggested method to run the parser. Method 4 can go with merge_results into a helper scripts header.

```
## How to use it
mkdir -p ./tmp/parser-output/output_folder_name

python ./refparse.py \
    --scraper-file "s3://datalabs-data/scraper-results/msf/20190117.json" \
    --references-file "path/to/references.csv" \
    --model-file "s3://datalabs-data/reference_parser_models/reference_parser_pipeline.pkl" \
    --output-url "file://./tmp/parser-output/output_folder_name"
```
What do you think? @lizgzil @peter337 @hblanks @SamDepardieu ?

**Comment by hblanks** [comment]
Yes, please. "There can be... only one!"

Note this is tracked in trello at https://trello.com/c/GknWiDll/622-consolidate-4-methods-for-running-the-parser
